FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime

COPY . .

RUN apt-get update
RUN apt-get install -y build-essential
RUN pip3 install -r requirements.txt

CMD ["python3", "min_working_example.py"]

# build with: docker build -t minimal -f Dockerfile.minimal .
# start with: docker run --gpus all minimal